/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes the state and basic information about one cycle highway (Radschnellverbindung)
 */
export type MetaSchemaRSV = {
  [k: string]: unknown;
} & {
  /**
   * Distinct id for every cycle highway.
   */
  id: string;
  general: {
    ref?: string;
    name?: string;
    from: {
      city?: string;
      federalState?: string;
      [k: string]: unknown;
    };
    to: {
      city?: string;
      federalState?: string;
      [k: string]: unknown;
    };
    description?: string | null;
    source?: string | null;
    stand: string;
    length: number;
    [k: string]: unknown;
  };
  /**
   * @minItems 1
   */
  stakeholders?: [
    {
      name: string;
      roles: [] | ["communication" | "authority" | "construction_company"];
      description?: string;
      [k: string]: unknown;
    }
  ];
  state: "idea" | "agreement_process" | "planning" | "in_progress" | "done";
  detail_level?: "exact" | "approximated" | "corridor";
  /**
   * Year or date when building of all segments have been done.
   */
  finished: string | null;
  cost: string | number | null;
  references?: {
    osm_relation?: number;
    website?: string | null;
    copyright_geometry?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
