/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes the state and basic information about one cycle highway (Radschnellverbindung)
 */
export interface MetaSchemaRSV {
  /**
   * Distinct id for every cycle highway.
   */
  id: string;
  general: {
    ref?: string;
    name?: string;
    from: string;
    to: string;
    description?: string;
    /**
     * Defines an URL slug
     */
    slug: string;
    [k: string]: unknown;
  };
  stakeholders?:
    | []
    | [
        {
          name: string;
          roles: [] | ["communication" | "authority" | "construction_company"];
          description?: string;
          [k: string]: unknown;
        }
      ];
  status: "idea" | "agreed" | "planning" | "in_progress" | "done" | "discarded";
  planning_phase?: "pilot" | "preliminiary" | "design" | "approval" | "execution" | "building";
  detail_level?: "exact" | "approximated" | "corridor";
  /**
   * Year or date when building of all segments have been done.
   */
  finished?: string;
  cost?: string | number;
  references?: {
    osm_relation?: number;
    website?: string;
    "copyright:geometry"?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
